Fixed indentation

diff --git a/utils/clone-git-repos b/utils/clone-git-repos
--- a/utils/clone-git-repos
+++ b/utils/clone-git-repos
@@ -11,45 +11,45 @@ COMPONENT_FOLDER=TRUE
 VALID_ARGS=FALSE
 
 create_new_group() {
-    if [ $GROUP_FOLDER = "TRUE" ]; then
-        NEW_DIR=${CLONEDIR}/$1
+  if [ $GROUP_FOLDER = "TRUE" ]; then
+    NEW_DIR=${CLONEDIR}/$1
 
-        mkdir -p $NEW_DIR
-        cd $NEW_DIR
+    mkdir -p $NEW_DIR
+    cd $NEW_DIR
 
-        CURRENT_GROUP=$NEW_DIR
-        CURRENT_DIR=$NEW_DIR
-    else
-        CURRENT_DIR=$CLONEDIR
-        cd $CURRENT_DIR
-    fi
+    CURRENT_GROUP=$NEW_DIR
+    CURRENT_DIR=$NEW_DIR
+  else
+    CURRENT_DIR=$CLONEDIR
+    cd $CURRENT_DIR
+  fi
 }
 
 create_new_component() {
-    if [ $COMPONENT_FOLDER = "TRUE" ]; then
-        NEW_DIR=${CURRENT_GROUP}/$1
+  if [ $COMPONENT_FOLDER = "TRUE" ]; then
+    NEW_DIR=${CURRENT_GROUP}/$1
 
-        mkdir -p $NEW_DIR
-        cd $NEW_DIR
+    mkdir -p $NEW_DIR
+    cd $NEW_DIR
 
-        CURRENT_DIR=$NEW_DIR
-    fi
+    CURRENT_DIR=$NEW_DIR
+  fi
 }
 
 clone_git_repo() {
-    NEW_DIR=$(basename $1)
-    if [ -d "$NEW_DIR" ]; then
-        echo -e "\033[0;35mRepo \033[0;36m$1\033[0;35m already cloned in \033[0;33m${CURRENT_DIR}/${NEW_DIR}\033[0m"
-        return
-    fi
+  NEW_DIR=$(basename $1)
+  if [ -d "$NEW_DIR" ]; then
+    echo -e "\033[0;35mRepo \033[0;36m$1\033[0;35m already cloned in \033[0;33m${CURRENT_DIR}/${NEW_DIR}\033[0m"
+    return
+  fi
 
-    echo -e "\033[0;32mCloning repo \033[0;36m$1\033[0;32m into \033[0;33m${CURRENT_DIR}/${NEW_DIR}\033[0m"
-    #git clone ssh://${USERNAME_FOR_GIT}@gerrit-server:29418/$1
-    cp ${CLONEDIR}/commit-msg ${CURRENT_DIR}/${NEW_DIR}/.git/hooks/
+  echo -e "\033[0;32mCloning repo \033[0;36m$1\033[0;32m into \033[0;33m${CURRENT_DIR}/${NEW_DIR}\033[0m"
+  #git clone ssh://${USERNAME_FOR_GIT}@gerrit-server:29418/$1
+  cp ${CLONEDIR}/commit-msg ${CURRENT_DIR}/${NEW_DIR}/.git/hooks/
 }
 
 usage() {
-    cat <<EOF
+  cat <<EOF
 Script to clone a bunch of repositories into the current directory
 
 Usage:
@@ -80,50 +80,50 @@ TIPS:
   # Note that your ssh key may be called something else
 
 EOF
-    exit
+  exit
 }
 
 if (( $# == 0 )); then
-    usage
+  usage
 fi
 
 while getopts ":gu:cfh" opt; do
-    case $opt in
-        g)
-            GROUP_FOLDER=TRUE
-            COMPONENT_FOLDER=TRUE
-            VALID_ARGS=TRUE
-            ;;
-        c)
-            GROUP_FOLDER=FALSE
-            COMPONENT_FOLDER=TRUE
-            VALID_ARGS=TRUE
-            ;;
-        f)
-            GROUP_FOLDER=FALSE
-            COMPONENT_FOLDER=FALSE
-            VALID_ARGS=TRUE
-            ;;
-        u)
-            USERNAME_FOR_GIT=$OPTARG
-            ;;
-        h)
-            usage
-            ;;
-        \?)
-            echo "Invalid option: -$OPTARG" >&2
-            exit 1
-            ;;
-        :)
-            echo "Option -$OPTARG requires an argument." >&2
-            exit 1
-            ;;
-    esac
+  case $opt in
+    g)
+      GROUP_FOLDER=TRUE
+      COMPONENT_FOLDER=TRUE
+      VALID_ARGS=TRUE
+      ;;
+    c)
+      GROUP_FOLDER=FALSE
+      COMPONENT_FOLDER=TRUE
+      VALID_ARGS=TRUE
+      ;;
+    f)
+      GROUP_FOLDER=FALSE
+      COMPONENT_FOLDER=FALSE
+      VALID_ARGS=TRUE
+      ;;
+    u)
+      USERNAME_FOR_GIT=$OPTARG
+      ;;
+    h)
+      usage
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
 done
 
 if [ $VALID_ARGS = "FALSE" ]; then
-    echo "None of the flags -g, -c or -f was provided"  1>&2
-    exit 1
+  echo "None of the flags -g, -c or -f was provided"  1>&2
+  exit 1
 fi
 
 
@@ -133,4 +133,3 @@ fi
 
 
 rm ${CLONEDIR}/commit-msg
-
diff --git a/utils/jumphost/getdb b/utils/jumphost/getdb
--- a/utils/jumphost/getdb
+++ b/utils/jumphost/getdb
@@ -17,38 +17,38 @@ declare -A jumphosts
 # equal sign.
 # Format is "jumphost host1 local_port1 dest_port1 host2 local_port2 dest_port2 host3 local_port3 dest_port3 ..."
 jumphosts=(
-    # Alias              Jumphost            Destination_host             Local_port  Destination_port
-    ["dummy_name_1"]="   jumphost_or_ip1     destination_host_or_ip11     12345       5555"
-    ["dummy_name_2"]="   jumphost_or_ip2     destination_host_or_ip21     12345       5555"
-    ["dummy_name_3"]="   jumphost_or_ip3     destination_host_or_ip31     12345       5555
-                                             destination_host_or_ip32     12346       5555"
-    ["dummy_name_4"]="   jumphost_or_ip4     destination_host_or_ip41     12345       5553"
-    ["dummy_name_5"]="   jumphost_or_ip5     destination_host_or_ip51     12345       5554"
+  # Alias              Jumphost            Destination_host             Local_port  Destination_port
+  ["dummy_name_1"]="   jumphost_or_ip1     destination_host_or_ip11     12345       5555"
+  ["dummy_name_2"]="   jumphost_or_ip2     destination_host_or_ip21     12345       5555"
+  ["dummy_name_3"]="   jumphost_or_ip3     destination_host_or_ip31     12345       5555
+                                           destination_host_or_ip32     12346       5555"
+  ["dummy_name_4"]="   jumphost_or_ip4     destination_host_or_ip41     12345       5553"
+  ["dummy_name_5"]="   jumphost_or_ip5     destination_host_or_ip51     12345       5554"
 )
 
 create_ssh_forwarding_command() {
-    local FORWARD_COMMAND JUMPHOST HOST LOCAL_PORT DEST_PORT REST
-    IFS=$' \n' read -d '' JUMPHOST REST <<< $2
+  local FORWARD_COMMAND JUMPHOST HOST LOCAL_PORT DEST_PORT REST
+  IFS=$' \n' read -d '' JUMPHOST REST <<< $2
 
-    if [ -z "$REST" ]; then
-        echo "The entry for \"$1\" is poorly formatted. Exiting..." 1>&2
-        exit
+  if [ -z "$REST" ]; then
+    echo "The entry for \"$1\" is poorly formatted. Exiting..." 1>&2
+    exit
+  fi
+
+  FORWARD_COMMAND="ssh $JUMPHOST -N -o ServerAliveInterval=60 "
+  # Add all forwarding parameters
+  while [ -n "$REST" ]; do
+    IFS=$' \n' read -d '' HOST LOCAL_PORT DEST_PORT REST <<< $REST
+
+    if [ -z "$LOCAL_PORT" -o -z "$DEST_PORT" ]; then
+      echo "A port for \"$HOST\" is missing. Exiting..." 1>&2
+      exit
     fi
+    FORWARD_COMMAND="$FORWARD_COMMAND -L ${LOCAL_PORT}:${HOST}:${DEST_PORT} "
+  done
 
-    FORWARD_COMMAND="ssh $JUMPHOST -N -o ServerAliveInterval=60 "
-    # Add all forwarding parameters
-    while [ -n "$REST" ]; do
-        IFS=$' \n' read -d '' HOST LOCAL_PORT DEST_PORT REST <<< $REST
-
-        if [ -z "$LOCAL_PORT" -o -z "$DEST_PORT" ]; then
-            echo "A port for \"$HOST\" is missing. Exiting..." 1>&2
-            exit
-        fi
-        FORWARD_COMMAND="$FORWARD_COMMAND -L ${LOCAL_PORT}:${HOST}:${DEST_PORT} "
-    done
-
-    # The actual ssh command is run here
-    $FORWARD_COMMAND 1>&2
+  # The actual ssh command is run here
+  $FORWARD_COMMAND 1>&2
 }
 
 # Entry point to program
@@ -56,8 +56,8 @@ create_ssh_forwarding_command() {
 JUMPHOST_DATA="${jumphosts[$1]}"
 
 if [ -z "$JUMPHOST_DATA" ]; then
-    echo "The entry \"$1\" could not be found. Exiting..." 1>&2
-    exit
+  echo "The entry \"$1\" could not be found. Exiting..." 1>&2
+  exit
 fi
 
 create_ssh_forwarding_command "$1" "$JUMPHOST_DATA"
